language: python
matrix:
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
  allow_failures:
    - python: "nightly"
  
# command to install dependencies
install: 
  - pip install pytest mock
# command to run tests
script: py.test -v

